name: Test and Integrity Check

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  integrity:
    name: Check Bundle Integrity
    runs-on: ubuntu-latest
    container: shopware/development:7.4-composer-2
    env:
      APP_ENV: test

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: root

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: sw-blurhash
      - name: Set up Workspace
        uses: ./sw-blurhash/.github/actions/setup-workspace
      - name: Rebuild Administration and Storefront Bundle
        shell: bash
        working-directory: shopware
        run: |
          ./psh.phar storefront:build
          ./psh.phar administration:build
      - name: Rollup and transpile Blurhash chunks
        shell: bash
        working-directory: sw-blurhash
        run: |
          ./bin/build-blurhash.sh
      - name: Check Bundle Integrity
        shell: bash
        working-directory: sw-blurhash
        run: |
          echo "Following files differs from those commited:"
          git --no-pager diff --name-only --exit-code HEAD
